### ISSUE TITLE
[Bug]: <selling ingot at scrap yard>

### ISSUE THREAD

**Issue by Monkeyjamma1** [FuryFight3r/ScrappingSimulator#105]
### Describe the bug

when i go to sell an ingot at the scrap yard for example if i had 5 aluminum and 3 copper ingots in the ingot storage at the scrap yard. i go to sell the copper ingots all of the ingots turn into copper ingots that are in the ingot storage at the scrap yard. i have noticed this with aluminum to.

### Reproduction Steps

put some different types of ingots in the ingot storage at the scrap yard right before selling them. the pick one and sell it and all of then turn into the ingot you are selling.

### Expected behaviour

i espected to only sell the ingot i picked and not for all of them to turn into the ingot material i sold.

**Comment by Monkeyjamma1** [comment]
also when i go to sell more ingots i have noticed that the button does not work. i reload the game and the button works once and all my ingot come back into the ingot storage at the scrap yard. i can protentionaly keep doing that for infinite money which is a problem. it does not hold an accurate ingot count and material. im not sure if anyone else is having this issue

**Comment by FuryFight3r** [comment]
Hi there @Monkeyjamma1 and thank you for reporting this, I hope to have this fixed in the next v0.32.1 update 🙂👍

**Comment by FuryFight3r** [comment]
Hi the @Monkeyjamma1 

Thanks again for reporting this, I have added a temporary fix by disabling the Auto Sort part of the code and I will rework the way the Auto Sort works in the future, maybe by storing the current Ingot IDs in a seperate list, then clear the main list and then copy the temporary list, as I have found that actively modifying a list that is in use can cause issues, so hopefully I can figure out a work around, but disabling the Auto Sort should work now, just that there will be gaps in-between sold Ingots for the time being 🙂👍

**Comment by Monkeyjamma1** [comment]
Okay awsome, I tried getting into coding and game development and it's a
pain to learn and remember but you are doing a great job and I love the
game. If I find anything else I'll let you know.

**Comment by FuryFight3r** [comment]
@Monkeyjamma1 It is certainly a challenge, especially Solo Game Dev as it's not only coding, but sound design, modelling, 2d texturing, animating, web design, community management, news, marketing etc, but I think I am slowly getting there 🙂 
There are some pretty great guides on YouTube on how to make a basic game nowadays which I think can help people get into coding while also being fun 🙂 though one thing to note with these Tutorials is they use shortcuts when coding, to make it easier to display and explain, though in the long run it can be very poorly optimised and can lead newcomers into a trap of poor optimisation in their game due to most guides skipping over this step for simplicity sake.

But all I can say is if I can learn Game Dev basics anyone can 😅😅 just got to stick at it 🙂

**Comment by Monkeyjamma1** [comment]
I have noticed that when you are carrying a scrap electronics it freezes in
the air after approximately 8 seconds then you can pick it up agian and at
approximately 8 second it freezes agian. This happens with all scrap I pick
up so far.

**Comment by Monkeyjamma1** [comment]
This one it seams the scrap part does not fully get removed preventing me
from finishing the tear down. It just stays there and I can't do anything
to remove it. I can move the server but can't finish disassembling it. I
have only encountered it with the server scrap so far.

**Comment by Monkeyjamma1** [comment]
On the server bug were it didn't let me finish disassembling. I just loaded
into the game and the server was still there partially disassembled. I
noticed that some of the the scrap parts in it came back so I belive the
error has to do with the 8gb ddr3 ram stick and the mother board
interactions.

**Comment by FuryFight3r** [comment]
@Monkeyjamma1 I can certainly understand it being hard to remember a lot of the functions and methods with Unity as I have a terrible memory 😂 
But Roblox is a great way to get into coding I feel, I did end up making a couple of games on there, a Building/Financial one and ofcourse an Obby 😅 it's truly amazing what people can make on there and the flexibility it and the community provides 🙂

I do apologise for the bugs in the new update, I was actually aware of the Objects freezing after carrying them (which is due to the new way that Objects Physics are enabled/disabled) which ofcourse Id forgotten to patch before releasing the update 😅 so after dropping an object a 10 second timer begins and if it's not interacted within 10 seconds the object becomes Static and the Physics are disabled which greatly improves performance when a lot of Physics based objects are active at one time, but for some reason that timer is now also starting when the object is picked up, hopefully I can track down the source of this and the disassembly issues and have a patch out asap 🙂👍

**Comment by Monkeyjamma1** [comment]
What is your roblox name I'll have to look up your games and play them. I
couldn't imagine how much stuff you have to check to make sure everything
is working in a game but you are doing a great job. I did find a few more
bugs if you want me to share with you.

**Comment by FuryFight3r** [comment]
I believe my username would have been FuryFight3r 🙂
