### ISSUE TITLE
[Bug]: the barriers are broken

### ISSUE THREAD

**Issue by DARTS232** [FuryFight3r/ScrappingSimulator#111]
### Describe the bug

when you drop a small object by a barrier it teleports home. which is fine but if there is a hole might be bad for the driving part

### Reproduction Steps

1.pick up dvr or other small ewaste
2.walk to barrier
3.drop ewaste so it falls along the invisble wall of the barrier
4.waste should fall through earth and return home

### Expected behaviour

no teleporting home or falling throuygh earth unless this is a feature

### Screenshot(s)/Video(s)

![3](https://user-images.githubusercontent.com/131835320/235280751-ae4f2d06-87d6-41ef-ad85-2f30d688df0d.png)

### Console output

![4](https://user-images.githubusercontent.com/131835320/235280745-e025d204-248c-4294-955a-90b2ee88403e.png)

**Comment by FuryFight3r** [comment]
Hi @DARTS232 and thank you for reporting this.

Is this with every barrier or at a specific spot in the map?

**Comment by DARTS232** [comment]
every barrier

**Comment by DARTS232** [comment]
yes i did try for ummm... science

**Comment by DARTS232** [comment]
havent tried the long one by the house

**Comment by FuryFight3r** [comment]
Thank you, I will look into this 🙂👍

**Comment by FuryFight3r** [comment]
@DARTS232 I haven't yet been able to replicate this, the closest I had gotten was when dropping objects on the beach they would tip 90° though is still not far enough to get collected by the Lost and Found Box

Is there something I am doing wrong?
https://youtu.be/v75Gz_53CcI

Would you be able to provide a short clip of how you are able to produce this bug?

**Comment by FuryFight3r** [comment]
Hi there @DARTS232 
Due to this issue being open for 3 months with no further information being provided it will now be closed.
With the provided information I was unable to replicate the issue and other users have reported that the barriers are all working as expected.
If you are still experiencing the Bug feel free to re-open this issue providing more information on how I could replicate the Bug to be able to Patch and Fix it :)
