### ISSUE TITLE
[Suggestion]: high wattage transformers found in microwaves are secured in place with screws

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#114]
### What is your Suggestion?

in real life, when you open the cover of a microwave, you'll find that the iconic massive transformer is usually screwed down in place. removing it with a pair of pliers does not seem to feel very realistic considering just how well this thing is usually screwed down, you couldn't get it off with a sledgehammer if you tried.

the type of transformer currently used in the game is not the same transformer either, the transformer used in microwaves is usually akin to a massive iron block with 2 visible phases of copper wire.

### How will this suggestion fit into the Scope of Scrapping Simulator?

since you're already planning on adding wires and the oh-so-iconic magnetron, why not make the other iconic component found in microwaves a bit more accurate as well?

### How would the Game and Community benefit from this suggestion?

The microwave's transformer is such an iconic piece that it is fundamental that it should look right in my opinion.

**Comment by FuryFight3r** [comment]
Hi @aus2004 and thank you for your suggestion, I agree it is a little weird pulling a ~1-2kg Transformer with a pair of pliers is a bit far fetched, I can certainly see about reworking the large Transformer model to include tabs that allow it to be screwed and mounted to a solid foundation, as apose to its smaller variants only being secured by their solder connections, which once the screws holding the large Transformer have been removed I could make it use the 'Hand' tool instead of the Pliers to remove the Transformer itself 🙂👍

**Comment by FuryFight3r** [comment]
Thanks again for Suggesting this, this should now be fixed in the [v0.33.1 Update](https://store.steampowered.com/news/app/1496640/view/3663162167647668910?l=english) 🙂👍
