### ISSUE TITLE
[Suggestion]: <Add Title Here>

### ISSUE THREAD

**Issue by gold500006** [FuryFight3r/ScrappingSimulator#131]
### What is your Suggestion?

i like to see save slots so you can save the game like in slot 1 the save game agane in slot 2 2 times this has happend i play the game for a week i had loads of things unlock  most of the parks and skills lots of money i keep saveing the game then this happend the game crash on saveing screen it say saveing comleted 100 percent it has not the game crash i turn game off load game and lost me game save i have to start all over agane with new game first time i play game it was for a month and game crash on saveing screen if there was game slots you can save game in slot 1 and 2 if game save crash you still have a copy in slot 2 then i wouldnt keep starting new games and starting over all the time 

### How will this suggestion fit into the Scope of Scrapping Simulator?

well 2 saves slots you wont lose your game save if 1 game save crash you had 2 copys of the same save the game needs save slots 

### How would the Game and Community benefit from this suggestion?

well save slots will benerfit if you lose one game save you have another save so you dont lose nothing everone would be happy thay wont lose all what there have done in the game

**Comment by FuryFight3r** [comment]
Hi there @gold500006,
I would like to have a Save Slot mechanic at some stage, though with this issue I think the better route would be to fix the bug rather than avoiding it, that way you can play the entire game without it crashing as appose to just repeating the first half

I have noticed a trend being that a lot of players reporting recent issues have their System displaying number values as 15,75 rather than 15.75 which this seems to cause issues with a handful of in-game systems, despite counter measures put in many updates ago at an attempt to fix this.

I only say this as I have bug and stress tested the latest build of the game (being v0.34) for countless hours and unfortunately I haven't been able to replicate any of the recently created bug reports, which I believe this due to the difference in digits (what would be shown to me as 15.75 is being shown to others as 15,75) is creating errors within these systems when requesting numbers, which errors shown in bug reports in the past often reflect not being able to convert say: 34,0 into a number value, as the numbers my code is requesting are meant to be in 34.0 format not 34,0 format.

If I can gather more information about why certain players have numbers shown as 123,00 rather than 123.00, whether its the Language settings selected within their windows settings, or if its some Region specific feature encoded in the hardware that makes windows display numbers that way, If I knew more about being able to create an environment similar to the users experiencing the problem, like a Virtual Machine for example that is setup to mimic this number difference, that way I can physically see the error in action and exactly what is causing it - as at the moment I am just chasing the wind, without being able to replicate and inspect these bugs myself it's near impossible to fix them as I am almost just guessing when it comes to creating a patch for these type of issues.

If you are able to provide more details about the issues you are facing it might help me in tracking down what is going wrong within the code and aid in creating a patch for it - One way is providing any and all errors (Red '!' Logs) that are shown when pressing [F5] when something goes wrong in-game, in most cases all white and yellow logs can be ignored however, Red Error Logs are generally a clear indicator of something that has failed or become broken/frozen.
Keep in mind this Debug Log is only relative to the Game Session, after closing the game the logs produced from that session are dumped to file and cleared and can no longer be accessed without digging through the game files
