### ISSUE TITLE
[Suggestion]: Link Ingot shelf to Desktop Computer Ingot Market

### ISSUE THREAD

**Issue by JackDaring** [FuryFight3r/ScrappingSimulator#14]
### Suggestion;

Instead of dragging ingots into the computer monitor. It would be nice if the computer could access your ingot shelf storage and you could sell directly in bulk from there.

### Why is this a good suggestion?

I think it's a good quality of life improvement.

**Comment by FuryFight3r** [comment]
Hi JackDaring,

That is a good idea, however I am still on the fence (trying to decide) whether or not to keep the PC Ingot Sale System for the later game, the only reason this is in the game was that during the DEMO there were no other means of selling Ingots at the time and the intention was to convert it to an eBay style market, where you would set your own desired price, being that if the price is low, it will sell quickly and if it's overpriced it may never sell for that price, possibly also a bidding system that works similar to eBay, because the PC Ingot Sale is quite OP as it stands and it almost makes the Scrap Yard pointless in regards to Ingots, as you can simply just sell all your Ingots at the PC instantaneously, so there's little to no point in traversing all the way to the scrap yard.

The only issue being is this would be no easy task and if I went the eBay style route, I could imagine it would be highly requested to be able to add normal items here also, making it even more so of a task. 

Nonetheless this may be a great addition for the future :)

**Comment by FuryFight3r** [comment]
Hi there @JackDaring and thank you for your suggestion, Unfortunately as of v0.36 the PC Ingot Market has been removed and is no longer active within the game, I feel keeping Material/Ingot Sales more centralised to the Scrap Yard will be more clear and easy for New Players to understand, while also being more streamlined to manage the economy and player progression with a bit more ease, nevertheless thank you again for Suggesting this and I look forward to your future suggestions :)
