### ISSUE TITLE
[Bug]: Ewaste objects stop generating randomly when playing the game for a long time

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#18]
### Describe the bug

I have **zero** clue what causes this to happen, but after sitting in game for around more than an hour _(i didn't actually count, i'm estimating here),_ Ewaste objects just cease to generate around trashcans. It's fixed by save/exit/start but it is a very interesting bug.

### Reproduction Steps

1. literally sit in game for a _really_ long time. it'll happen _eventually_.

### Expected behaviour

Ewaste objects stop appearing around trashcans.

**Comment by FuryFight3r** [comment]
Hi there Aus2004,

I have heard of this bug a few times in the past, though have never actually experienced it myself, the coding for the respawning of objects suggests that it's on a permanent loop, which 'should' never stop looping/producing objects, if something were to have gone wrong within the code it should print an error in the console but have yet to see any with other reports also so I will try do some tests on this once I am able to return back to developing the game, see if any errors are produced and go from there, if no obvious error is produced I may be able to add a check in the code that if it notices no spawn timer is active it attempts to restart it.

Thank you for reporting this I am hoping to have it fixed in the next update 🙂

**Comment by FuryFight3r** [comment]
Hi again Aus2004,
Thanks again for reporting this, after doing a heap of testing I found it was some old code that was making the script stop it repetitive nature if it so happened to roll the dice on a Bin that does not spawn eWaste. This has now been fixed in the v0.28.6 update :)
