### ISSUE TITLE
[Bug]: Gold Silver beaker/Airrator 

### ISSUE THREAD

**Issue by Merlin8326** [FuryFight3r/ScrappingSimulator#24]
### Describe the bug

The beaker for the gold silver deposit no longer works. 

It worked fine at start normal and have used it prior to this. After several reloads and launches it no longer is able to be added to or shows up at all. 

### Reproduction Steps

Unknown steps required

### Expected behaviour

Be able to add Gold to begin process.

**Comment by FuryFight3r** [comment]
Hi there Merlin8326,
Thank you for reporting this issue, I will have this patches and fixed in the next update 🙂

**Comment by FuryFight3r** [comment]
Hi again Merlin8326,

I just wanted to let you know that this issue with the Beaker should be fixed in the v0.30 Major Update, if you are still experiencing some issues with the beaker, you now have the ability to type 'reset_beaker' inside the command panel (accessed by pressing the Tilde [~] Key) to reset the beaker back to default.

Thanks again for reporting this bug! :)
