### ISSUE TITLE
[Bug]:Item ye carry and release finger at pawn shop, close to wall go through wall and cant be picked up.

### ISSUE THREAD

**Issue by Kosuchi** [FuryFight3r/ScrappingSimulator#25]
### Describe the bug

Picked up an "laptop", went to pawn shop. Really close to wall i released to sell it, phased to inside wall (laptop) and could not repick it or sell it.

### Reproduction Steps

1. Find a item on street
2. Pick it up and go pawn shop.
3. Go to "sell box" against wall
4. Release item.
5. Try to see it phases.

### Expected behaviour

Bug will phase item out of reach inside wall.. what i really expect function to do against leaning wall, is it to "bounce" to floor, not to phase.

**Comment by FuryFight3r** [comment]
Hi there Kosuchi,
Thank you for reporting this, I will look into this and see about adding physics to objects that are being carried rather than having them locked to a fixed carry position 🙂 I agree 100% that objects shouldn't be able to phase though other objects while being carried, the reasoning behind this was that objects that have colliders/physics really affect the player in weird ways if the object collides with the player (for example if you are holding a server and look all the way down, it can sometimes lift the player up into the air, or limit the players movement, as it is interfering with the players collider), I will certainly have a play around with this and see if I can make it so the objects being carried can collide with all objects except for the player.

**Comment by FuryFight3r** [comment]
Hi again Kosuchi,
I just wanted to let you know that these issues with carrying objects should be fixed in the latest Major Update v0.30

Thanks again for reporting this! :)
