### ISSUE TITLE
[Bug]: <The new buttons for command panel "F1" "`" are note working proberly>

### ISSUE THREAD

**Issue by Nerdyboydk** [FuryFight3r/ScrappingSimulator#32]
### Describe the bug

When i press "F1" or "`" nothing happens

### Expected behaviour

The command panel to appear

**Comment by FuryFight3r** [comment]
Hi there NerdyBoyDK,
Thank you for reporting this, Are you able to provide what keyboard layout you are using? As this should help me in diagnosing why it doesn't work for you.
Here in Australia we use the US Standard Keyboard Layout, I understand that other regions have different layouts, though there could be many reasons this is happening.
Have you also tried holding [Shift]+[`] or [Shift]+[~] or even [FN]+[F1] if you are using a Laptop or otherwise Function orientated Function key setup.
Below is a template of the 2 major Keyboard layouts US and UK, in my instance, using the US layout, my button to Oppen the command prompt is the 'Backquote' (`) button under escape, or the same button, but holding Shift to make it a Tilde key press, otherwise Just F1 or FN+F1 (if I were to be on a laptop for example)
![Keyboard Layout](https://user-images.githubusercontent.com/44615800/175539364-c1e20433-1c10-4f4b-bcb0-cb91747e491d.png)

**Comment by Nerdyboydk** [comment]
I tried all of your suggested key combinations but they unfortunately did not work.

![Skærmbillede 2022-06-24 192421](https://user-images.githubusercontent.com/104791139/175611582-fce1c503-0264-44a0-938f-33b6ceb68e4c.jpg)
(I have a danish key layout)
(Hope the image is clear enough)

**Comment by Nerdyboydk** [comment]
(Btw the cay to the left besides key "1" contains:
½
§

**Comment by FuryFight3r** [comment]
> I tried all of your suggested key combinations but they unfortunately did not work.
> 
> ![Skærmbillede 2022-06-24 192421](https://user-images.githubusercontent.com/104791139/175611582-fce1c503-0264-44a0-938f-33b6ceb68e4c.jpg)
> (I have a danish key layout)
> (Hope the image is clear enough)
> (By the way the key to the left besides key "1" contains:
> ½
> §

Hi NerdyBoyDK, thank you for sharing that :) 
I will see if I can use the [½] or [§] as a registered keybind for the command panel and hopefully have this working for you in the next HotFix :)

**Comment by Nerdyboydk** [comment]
> > I tried all of your suggested key combinations but they unfortunately did not work.
> > ![Skærmbillede 2022-06-24 192421](https://user-images.githubusercontent.com/104791139/175611582-fce1c503-0264-44a0-938f-33b6ceb68e4c.jpg)
> > (I have a danish key layout)
> > (Hope the image is clear enough)
> > (By the way the key to the left besides key "1" contains:
> > ½
> > §
> 
> Hi NerdyBoyDK, thank you for sharing that :) I will see if I can use the [½] or [§] as a registered keybind for the command panel and hopefully have this working for you in the next HotFix :)

 Thanks FuryFight3r for replying.
I am already looking forward to the next Hotfix.
But until then stay safe and have a lovely day

- NerdyBoyDK

**Comment by FuryFight3r** [comment]
Hi there NerdyBoyDK,
This issue has been fixed upon in the v0.30.1 Hot Fix (I was unable to find keybinds for the Half and other icon, however F1 should work on every layout now).

https://store.steampowered.com/news/app/1496640/view/3358011588166204161

Thank you for reporting this and helping the game become better.

**Comment by Nerdyboydk** [comment]
Hi FuryFight3r i am happy to finally announce its working!
![Skærmbillede 2022-06-26 213202](https://user-images.githubusercontent.com/104791139/175830838-8068ac06-895d-42e6-8c3f-8abcbd7c25fd.jpg)
Its been quite a journy hahaha
Have a great day FuryFight3r !
