### ISSUE TITLE
[Bug]: Crucible Bug

### ISSUE THREAD

**Issue by CrazyJamie1** [FuryFight3r/ScrappingSimulator#33]
### Describe the bug

So I bought the crucible from the shop, but it didn't give me a crucible and when trying to reset the crucibles position it tells me I don't own one

### Reproduction Steps

1. Go to shop
2. Buy crucible

### Expected behaviour

Well I expected to have a crucible, I guess

### Screenshot(s)/Video(s)

![Bug e 1](https://user-images.githubusercontent.com/108179614/175771374-31114bfd-1a8f-4234-ae1a-5c943c523d26.JPG)
![Bug e 2](https://user-images.githubusercontent.com/108179614/175771377-7d1f696c-f20a-4c85-b231-6087c0388bd4.JPG)

### Console output

I missed the console errors as I closed the game without thinking

### Player Logs

[Player.log](https://github.com/FuryFight3r/ScrappingSimulator/files/8984587/Player.log)
[Player-prev.log](https://github.com/FuryFight3r/ScrappingSimulator/files/8984588/Player-prev.log)

**Comment by FuryFight3r** [comment]
Hi there Crazy Jamie,
Thank you for reporting this.
This should be fixed in the v0.30.1 HotFix that will be coming out very shortly. Something went wrong with the system I made that was suppose to remove outdated objects and replace them with new ones, for some weird reason the crucible, if not owned by the player would be entirely deleted from the game, if the player did own the crucible it sometimes randomly doubled or tripled the amount of crucibles active, this confusing the furnace as to which crucible to look for.
You won't need to purchase the crucible again after this next update, as the Hardware store should recognise that you are suppose to own 1 and the new system I have in place will create a brand new one for you if there isn't already one in the world.

**Comment by FuryFight3r** [comment]
Hi there CrazyJamie,
This issue has been fixed in the v0.30.1 Hot Fix.

https://store.steampowered.com/news/app/1496640/view/3358011588166204161

Thank you for reporting this and helping the game become better.
