### ISSUE TITLE
[Suggestion]: Lower the window height in the garage

### ISSUE THREAD

**Issue by JackDaring** [FuryFight3r/ScrappingSimulator#40]
### Suggestion;

This is silly but I can't see the ocean view from the window in the garage without jumping. I'm a tall person in real life and this seems so silly. 

### Why is this a good suggestion?

Ocean views are nice.

**Comment by FuryFight3r** [comment]
Hi Jack,
Thank you for your suggestion, I completely agree, I am a little torn about the Current player House and Garage designs as they are from a different asset pack to the Synty Studios ones (Stores, Neighbour Houses etc) and I feel they don't really suit the rest of the Low Poly game design.
Just as a quick fix I could certainly see about lowering the window in the current Garage, but long term I would like to create a new house/garage that flows with the rest of the game design 🙂

**Comment by FuryFight3r** [comment]
Hi there Jack,
Thanks again for suggesting this, I have since lowered the entire top half of the garage so the window sits a little lower, I did attempt to modify the actual Model however this caused big problems with the textures, so just cheated a little and lowered the garage a little ;)

https://store.steampowered.com/news/app/1496640/view/3380531490309848653
