### ISSUE TITLE
[Suggestion]: Add material hopper at scrapyard

### ISSUE THREAD

**Issue by JackDaring** [FuryFight3r/ScrappingSimulator#41]
### Suggestion;

With buckets of materials, it would be nice to have some way to quickly offload them in the scrapyard. Considering the amount of empty real estate in the yard. What if we added some sort of hopper that you could place your bucket to quickly transfer everything without having to add it to your inventory first?

### Why is this a good suggestion?

This would be helpful if you wanted to clear materials quickly and efficiently

**Comment by FuryFight3r** [comment]
Hi Jack,
Thank you for the great suggestion, I was playing around with this a little back when I added the ability to drop the Ingot Carry Box on the Green Ingot Collector Box, but was a little torn about how to create a Shop Inventory to hold the transferred materials, which I found was quite inefficient and would just fill the screen with more bulk UIs in the scrap yard shop, but I think some sort of hopper like you mentioned just outside the building where you could place buckets and sell the contents, very similar to how the Pawn Shop Selling system currently works, where it displays a price so you have a choice to cancel or accept the price.

**Comment by FuryFight3r** [comment]
Hi there Jack,
Thanks again for suggesting this, I have since added this in the v0.30.3 Update. I think this will work really well with future plans of being able to throw waste material into the hopper to retrieve some missed metals and also dispose of the waste at the same time.

https://store.steampowered.com/news/app/1496640/view/3380531490309848653
