### ISSUE TITLE
[Bug]: Music isn't completely quiet

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#55]
### Describe the bug

in the settings, when you turn the music all the way down, you can still faintly hear it.

### Reproduction Steps

simply turn down the music and turn your audio way up. You'll still hear the music.

**Comment by FuryFight3r** [comment]
Hi there Aus,
Thanks for reporting this, I should be able to fix this by making so when the Volume slider is all the way down it completely disables the music, as Unity audio volumes work of a db value not an actual volume percentage where if the slider is at 0% it sets the output volume to -80db (which in some cases like this is not enough to completely mute the audio), nevertheless this should be an easy fix by checking if the slider is at 0% and if so the audio source can be muted entirely rather than just turned down.

**Comment by FuryFight3r** [comment]
Hi there Aus,

This has now been fixed in the [v0.30.6 Patch Update](https://store.steampowered.com/news/app/1496640/view/3395170090050452488) Thanks again for Reporting this :)
