### ISSUE TITLE
[Bug]: It is still possible to fly

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#56]
### Describe the bug

Despite the preventative measures, it is still possible to propfly.

### Reproduction Steps

grab a large object, such as a server or computer, run forwards and jump constantly. you'll start flying up. The wall method mentioned in a previous bug is still present as well. This is an easy fix, just make the player drop the ewaste object and unable to pick it up when they stand on it.

**Comment by FuryFight3r** [comment]
Hi there Aus,
Thank you for reporting this, yeah unfortunately I was unable to completely remove the ability to abuse this feature. Fixing this may seem simple however a lot of things are easier said than done when it comes to game dev. It's difficult to know (script wise) when a player is standing on-top of an object and using it to levitate, I could use collisions and look out for if the object collides with the player and drop the object if it touches the player, though even with just carrying the object normally it can bump into the player a handful of times by just walking/running, which would be very frustrating for players having to re-pickup the object every few steps. 
I could make it so that when the object is picked up it ignores all collision with the player, however each object has a main collider (that is used to pickup and attach to the disassembly table) and upward of 100 inner colliders for all the inner components (screws, MOBO, RAM etc) which would be very resource hungry to both find and disable each and every collider causing frame drops every time an item is picked up or dropped.
Nevertheless I will keep trying to improve/fix the new carrying system eventually I will find a stable/efficient way to handle it 🙂

**Comment by FuryFight3r** [comment]
Hi there Aus,

This has now been fixed in the [v0.30.6 Patch Update](https://store.steampowered.com/news/app/1496640/view/3395170090050452488) Thanks again for Reporting this :)

There may still be some rare cases that this can happen which I am still trying to diagnose but for now it seems quite stable
