### ISSUE TITLE
[Bug]: missing ingots

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#63]
### Describe the bug

this may be related to the old saves thing, but it is still noteworthy

### Screenshot(s)/Video(s)

![image](https://user-images.githubusercontent.com/101810723/186094228-38163369-f020-40b9-9b2c-2c1c5000b345.png)

**Comment by FuryFight3r** [comment]
Hi there Aus, 
That one is quite strange, as far as I was aware the Ingot Shelf had been fixed quite a few updates ago, before the v0.30 update.

Nevertheless I will look into what may be causing this and implement a patch asap.

Do you happen to have any info on the occurrence? 
Were the 2 missing Ingots of a different type? Or were they the same as the surrounding Ingots?
Could it be possible they were transported to the Bug Box? If not is there any error when pressing [F5] that would indicate that something went wrong with either the Shelf or the Ingot Objects themselves?

**Comment by aus2004** [comment]
this is a save issue, the ingots are most likely just of an invalid type, i can probably fix this just by emptying it, though it is incredibly interesting.

**Comment by aus2004** [comment]
as for what ingots they were? most likely 100g gold before the revamp of the whole crucible setup

**Comment by FuryFight3r** [comment]
Ah thank you for that, I know there is still sizing issues with the ingots, it seems each time they are added/removed from the Carry Box and or Shelf the size becomes a little tweaked, which I added code that detects this after looking at the object which should resize it back to default, it could be possible the ingots have become so miniscule they are essentially invisible which may fix itself once they are removed from the shelf.
With the HDD it is likely there was a brief hangup when loading the objects which caused the disassembly animations for the platters to partially play during the freeze time, before the animations could be disabled, I will have a look over the HDD prefab and make sure the animations are disabled by default 🙂

**Comment by aus2004** [comment]
alright, so yes they were just invalid ingots, taking them "off" the shelf made them disappear into thin air. It just said it was empty twice and then resumed dropping the other ingots from the shelf. Really interesting stuff.

**Comment by FuryFight3r** [comment]
Ahh dang, I apologise about that, I will have a look through the Shelf script and see if anything stands out.
However I am planning to completely rework the shelf and carry box methods very soon, from being Physical Storage to ID based storage which would be far more optimised, faster saving/loading and allow for possibly more shelving if changing to this method solves the current bugs.
The only thing that I am a little unsure about how to seamlessly transition the Old shelf to the New shelf without breaking saves. I am thinking I may have to make the new and old shelves separate objects entirely or at least a different script that handles the storage, so players continuing from an earlier saved version can remove all the physical Ingots from the old shelf and then maybe type a command or something that destroys the old shelf and enables the new ID based one, this way it should lower the chances of potentially losing Ingots due to them becoming corrupt or destroyed - Any new players/saves that purchase the shelf will receive the new ID based shelf by default.
Here's hoping I can come up with a solution for the ID Shelf asap and hopefully solve the pesky shelf bugs once and for all rather than just putting Band-Aids over a bad system 🤣

**Comment by aus2004** [comment]
okay, bringing this back up but these seem to somehow occur randomly in the middle of play, specifically on the top and middle shelves, i have no clue how they get there.

**Comment by FuryFight3r** [comment]
Hi Aus, sorry I had no idea you added another comment, I apologise about that.

Dang that's a shame 😔 I will definitely bump the Shelf Rework up in the list of things to do. After this v0.31 Update, the Shelf Rework will be top priority besides obviously urgent/high priority bug fixes.

Thank you for confirming something is still wrong with the shelf and it's not just a save issue I will have the reworked shelf in as soon as possible 👍

**Comment by aus2004** [comment]
i have figured it out, it's bad IDs, most likely an ID of zero, it does not overwrite ingots that were previously on the shelf.

**Comment by FuryFight3r** [comment]
Hi there Aus, I am not sure what you mean by this, as the system doesn't use any form of IDs (yet), it simply applies the Ingot Object to an available slot on the shelf, which a counter is used to keep track of the amount of Ingots that are contained in that shelf

**Comment by aus2004** [comment]
then it appears that the shelves are somehow counting certain empty spots as ingots (they don't exist though)

**Comment by FuryFight3r** [comment]
With the way the current system works if the shelf is empty the counter should be at 0, then adding any Ingot should increase the counter to 1 thus making the shelf aware that Slot-0 is now taken, adding a second Ingot will refer to the counter to find out which slot to place the next Ingot in the array of slots, which the counter basically handles the whole adding and removal process. For example if the current count is equal to 27, the shelf should know that a nother Ingot can be added to slot 27, or that if the Ingot is being removed it knows that '27-1=Slot-26' should contain the last added Ingot and the counter is then deducted as each Ingot is removed.

Do you mean that when adding an Ingot it may sometimes count as 2 rather than 1, thus skipping a/multiple slot(s)? As this could certainly be a possibiliy

**Comment by aus2004** [comment]
what appears to be happening is that the save file interprets empty slots as ingots sometimes for some reason. It's unusual to me, but that is what i've noticed. I've had it happen multiple times on shelves that have 0 ingots.

**Comment by FuryFight3r** [comment]
🤔 that is very strange indeed, once the current main Bugs are resolved I will start working toward the Shelf Restructure and hopefully solve the shelf issues once and for all 😅👍

**Comment by FuryFight3r** [comment]
Hi again @aus2004 thank you again for reporting this issue - The Ingot Shelf has had a complete overhaul in the [v0.32 Major Update](https://steamcommunity.com/games/1496640/announcements/detail/3640634660759680357) and now runs off an ID Based system which is a lot more Optimized both Overall and for Saving and Loading, which should solve the issues of the old Physical based System :) 👍
