### ISSUE TITLE
[Bug]: Loading complete applying data

### ISSUE THREAD

**Issue by NiKoLiNhO666** [FuryFight3r/ScrappingSimulator#64]
### Describe the bug

Hello, i have this kind of bug in scraping simulator that "Loading complete applying data" I hear game sounds but nothing happens. But when i restarted my save once everything worked but yea i was done playing saved the game and i wanted to play again today but i cant cuz this bug is here. Any idea how to fix it? I hear planes, boat, computer sounds etc but im stuck on loading screen

Error: FormatException: Input string was not in a correct format.
System.Number.ThrowOverflowOrFormatException (System.Boolean overflow, System.String overflowResourceKey) (at <d4cde64232cf45659d86aafa597faa77>:0)
System.Number.ParseSingle (System.ReadOnlySpan`1[T] value, System.Globalization.NumberStyles styles, System.Globalization.NumberFormatInfo info) (at <d4cde64232cf45659d86aafa597faa77>:0)
System.Single.Parse (System.String s) (at <d4cde64232cf45659d86aafa597faa77>:0)
saveLoadManager+<loadingProcess>d__17.MoveNext () (at <22cadbf7ce3f407d8b42cf3ca34c9e59>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <c6a0be87269c4a56aa4c8bc00101797f>:0)

**Comment by FuryFight3r** [comment]
Hi there Nikolinho,
I apologise about this. I have had another report similar to this but was unsuccessful in finding the issue.
If possible are you able to send through your save file so I can try and find what is going wrong?

**Comment by GizmosGaming** [comment]
![Scrap error](https://user-images.githubusercontent.com/112440633/187308063-b89da78e-a991-4fac-bdaf-c2cec687ad65.PNG)

This is what I get when I try to load the game.

**Comment by FuryFight3r** [comment]
> ![Scrap error](https://user-images.githubusercontent.com/112440633/187308063-b89da78e-a991-4fac-bdaf-c2cec687ad65.PNG)
> 
> This is what I get when I try to load the game.

Copied from Discord Chat:

I have a feeling it could be due to your System Language setting converting Period's to Comma's, which I have seen this in a few other users screenshots/videos where they're cash would be '$378,94' instead of '$378.94' which leads me to believe the Windows Language Setting could be causing this.

With the new version checker that was implemented a few updates ago, it saves only the Number part of the Game Version to your Save File, so when the game updates upon loading the users save file it checks the current Game Version against the Saved Version and I think this is where the loading script gives up as is cannot convert the Text "30,6" into a number "30.6" value that the script can use to check if the Current Game Version is greater than or equal to the Saved Version.

Which seems strange to me that the System Language can physically change values within the game, I may have to chat with the Unity community about this and see what can be done.

I am thinking I either make it so the script converts it back to an English decimal value (which I would have no clue how to do that, which I am hoping the Unity Community may be able to point me in the right direction), or possibly change the way the numbers are setup, rather than being 1 decimal number (30.6) I could make it 2 seperate non-decimal numbers being, Update: 30 - Revision: 6, which in-game will still be shown the way it is now, but just that it is saved/loaded as seperate numbers.

Nevertheless I will have a bit of a ponder on it and see which option would be better, I apologise that you have not been able to load up your save I hope to have this fixed asap and Thanks again for reporting this![IMG_20220829_153935.jpg](https://user-images.githubusercontent.com/44615800/187330183-1bb001b5-31bb-4a8f-bfb2-cee63c73e447.jpg)

**Comment by FuryFight3r** [comment]
Hi again @NiKoLiNhO666 and @GizmosGaming I hope you are both doing well.
I have just released the v0.30.7 Update which should hopefully Patch the issue with not being able to load in due to the version checker failing, I wasn't able to fully test this on a different System Language, though I was able to replicate it by modifying my Save Files data to save the Version as '30,6' rather than '30.6' and the code I added seems to successfully convert the comma back to a full stop/period and I was able to load back and continue off where I had saved, so hopefully it is the same outcome for the both of you (and anyone else facing this issue).
However if this still does not solve this issue please do let me know, I may need to look a bit deeper to the cause of the problem, the only Text Value being changed to a Number Value (Parse Conversion) during the load process is the version checker, which is what lead me to believe this was the cause of the problem, it also corresponds to @GizmosGaming's Screenshot of the error happening after loading the Crucible in the Error Logs as the Converting of the Version is the next action after as seen in my attached photo, Thank you both for reporting this and fingers crossed you can get back to Scrapping :)

![Screenshot_183](https://user-images.githubusercontent.com/44615800/189336500-5dace6a4-fff6-4500-a534-51d063b2e8c0.png)

**Comment by GizmosGaming** [comment]
I'm currently at work. But I will test it tonight when I get home. 🤞

**Comment by GizmosGaming** [comment]
The old save game didn't want to load. So I started a new game and played for a bit before saving. Exited the game and started it back up and hit load. It works. 
I took a screenshot just in case you wanted to see what happen when I tried to load the old save with the new patch.

![Scrap error 2](https://user-images.githubusercontent.com/112440633/189504170-dd0dd9f7-a0ac-4bc0-a4e8-10b32dbc86b8.PNG)

**Comment by FuryFight3r** [comment]
> The old save game didn't want to load. So I started a new game and played for a bit before saving. Exited the game and started it back up and hit load. It works. 
> I took a screenshot just in case you wanted to see what happen when I tried to load the old save with the new patch.
> 
> ![Scrap error 2](https://user-images.githubusercontent.com/112440633/189504170-dd0dd9f7-a0ac-4bc0-a4e8-10b32dbc86b8.PNG)
> 

That is quite strange that your old save didn't work with the new patch, but I am glad you can atleast load your new save now, if you do encounter any other problems please don't hesitate to let me know and I will do my best to have it fixed asap 🙂👍
