### ISSUE TITLE
[Bug]: (gameplay) crucible temperature resets to 0 when it hits the furnace temperature

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#67]
### Describe the bug

basically, something happened over the update that completely broke the heating mechanic of the crucible. It now resets to 0 whenever it hits the furnace temperature.

### Reproduction Steps

put ANYTHING in the crucible, i mean ANYTHING.
put it in the furnace and ignite it, wait for the crucible to hit the furnace temperature.
It should reset to zero when it reaches the furnace temperature.

### Expected behaviour

it's probably supposed to stay at the furnace temp rather than return to 0 instantly

### Screenshot(s)/Video(s)

https://user-images.githubusercontent.com/101810723/189414256-26ff7822-4612-455d-867d-abd6b68fc5e8.mp4

**Comment by FuryFight3r** [comment]
Hi there Aus,
Thank you for reporting this issue,

This one is really strange as the only thing changed for the update was adding some extra checks to check whether the Crucible is Inside the Furnace or not as well as if the gas runs out the Crucible will continue following the Furnace Temp rather than staying frozen at its current Temp.

Nevertheless, I will play around with this and see if I can replicate this issue, as there is only a select few events that force the Crucible to reset it's Temp to 0, being creating an Ingot, Removing the Metal from the Crucible or using the Reset Crucible Command, otherwise the only other movement is: if crucTemp > 0 and furnaceIsOn= false and or not InsideFurnace then gradually lower temp to 0, else if crucTemp < furnaceTemp and is InsideFurnace and furnaceIsOn then gradually 'play catch-up' with the furnace temp.

Hopefully I can have this fixed asap 🙂

**Comment by FuryFight3r** [comment]
Hi again Aus,
I have since fixed this issue within a small Hotfix Patch for [v0.30.7](https://store.steampowered.com/news/app/1496640/view/3328745165988370115)
Thank you for reporting this :)
