### ISSUE TITLE
[Bug]: (gameplay) another jank collision spot

### ISSUE THREAD

**Issue by aus2004** [FuryFight3r/ScrappingSimulator#74]
### Describe the bug

this one is not as bad as the purple box one in the hardware store, but it's still pretty funky

### Screenshot(s)/Video(s)

https://user-images.githubusercontent.com/101810723/189564582-653b1cb7-3087-4f78-86dd-21107615b57c.mp4

**Comment by FuryFight3r** [comment]
Hi there Aus,
Thank you for pointing this out, it seems small/tight gaps cause quite a few issues with the Character Controller (which was a purchased asset to rid the game of the standard Unity FPS Controller), especially with the Crouching mechanic, it seems to disable friction against objects, which I've found can make the player slide down a hill or even a very miniscule slope just by crouching which I think aids in the ability to use crouch to fall into otherwise inaccessible areas/traps (and thankfully being transported back to the Bug Box in most cases).

Nevertheless I will patch the known map issues and then maybe think about either reworking the current Controller or completely making a new Character Controller myself now that I have a bit better understanding and knowledge of Unity and C# Coding compared to a couple of years ago 😅

**Comment by FuryFight3r** [comment]
Hi again @aus2004 

The latest update [v0.30.8](https://steamcommunity.com/games/1496640/announcements/detail/3302850737224474511) should fix this bug.

Thanks again for reporting this 🙂
