### ISSUE TITLE
[Bug]: Scrapping Table Is Gone

### ISSUE THREAD

**Issue by Conndalf** [FuryFight3r/ScrappingSimulator#76]
### Describe the bug

When I loaded into my world I went and collected some items to scrap, but when i came back i noticed that my scrapping table was gone and there was a floating hard drive disc in the place where the desk should be

### Reproduction Steps

(im not 100% sure if this will work but this is what i think caused it for me)
1. Set Version To v0.30.3
2. Create World And Place Item On Table
3. Set Version To v0.30.7
4. Launch Same World Created In v0.30.3
5. Check Table

### Expected behaviour

When I launched my world i expected to see my table in the place it should have been, instead, it was missing with a hard drive disc in its place

### Screenshot(s)/Video(s)

![scrap](https://user-images.githubusercontent.com/113724841/190723989-12328052-a78f-4c2b-a508-a95f88066651.jpg)

### Console output

There Were No Errors Detected In The Console

### Player Logs

[Data.zip](https://github.com/FuryFight3r/ScrappingSimulator/files/9587017/Data.zip)
this includes all the player logs and the save file

**Comment by FuryFight3r** [comment]
Hi there Conndalf,

The Disassembly Table was moved to the Garage in the [v0.30.5 Skills and Perks Update](https://store.steampowered.com/news/app/1496640/view/3395170090042395241) 🙂

**Comment by Conndalf** [comment]
i do indeed see the table, but i believe the floating object is still an issue

**Comment by FuryFight3r** [comment]
Yeah that was a bug with that update, due to the way Objects are Saved/Loaded the object would have been saved in a 'able to disassemble' state, so after loading into the new version even though the table is not in the same location the data that was retrieved from the save file was saying there's and objects and such and such position, it can be disassembled etc.

I could possibly of added a patch to resolve this, though having to search and reference every interactable Item that was loaded into the game can be very resource hungry and can even crash the game if players have a lot of objects saved and or a lower end PC/laptop, so I am trying to use this fix method very sparingly.

To solve this issue you should be able to pickup the object and this will tell the game that this E Waste object can no longer be disassembled until it is placed back into the disassembly table. 
However if you are unable to interact with the object whatsoever then this may be an entirely different problem that I may need to look further into.

Nevertheless thank you for reporting this and please let me know if you have any issues 🙂👍
