### ISSUE TITLE
[Bug]: <Infinite loading at 80% (upgrades data)>

### ISSUE THREAD

**Issue by Etoilevent** [FuryFight3r/ScrappingSimulator#77]
### Describe the bug

Softlock at 80% chargement (upgrades data) after saving and closing the game (or returning to the menu)
it happens 3 times already and ad to alt+f4 and creat a new game. 

in each case, it was after i have buyed the furnace.
i need to try every step for confirming the bug but it take time (need to have money for the furnace etc)

don't remenber if the crucible was in the furnace when i've saved and quitted the game the first time, but it was in the second and third attempt. (and when i see the log, i think the crucible in the furnace is maybe the cause).

### Reproduction Steps

1-Playing like a normal player in scrapping Sim (no intente to break the game or others things for testing purpose)
2-buy a furnace and crucible, put the crucible in the furnace.
3-Save the game and quit the game (or return to the menu).
4-can't load your current party anymore.

### Expected behaviour

can load my party and continue my game without have to start a new game.

### Screenshot(s)/Video(s)

![2022-09-22 14_17_30-Scrapping Simulator](https://user-images.githubusercontent.com/49607897/191744601-07d1e1d9-aea6-40bd-916a-f6685f387423.png)

### Console output

FormatException: Input string was not in a correct format.
System.Number.ThrowOverflowOrFormatException (System.Boolean overflow, System.String overflowResourceKey) (at <d4cde64232cf45659d86aafa597faa77>:0)
System.Number.ParseSingle (System.ReadOnlySpan`1[T] value, System.Globalization.NumberStyles styles, System.Globalization.NumberFormatInfo info) (at <d4cde64232cf45659d86aafa597faa77>:0)
System.Single.Parse (System.String s) (at <d4cde64232cf45659d86aafa597faa77>:0)
saveLoadManager+<loadingProcess>d__17.MoveNext () (at <2b6c229980fb4a479b6df7e8521ad3b6>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <c6a0be87269c4a56aa4c8bc00101797f>:0)

**Comment by FuryFight3r** [comment]
Hi there Etoilevent thank you for reporting this.

This is really strange, this is the same error as the bug that should have been patched in the v0.30.7 update. Which I don't believe it has anything to do with the Furnace or Crucible, just that the error happened after the crucible was successfully loaded.

Are you able to confirm that you are possibly using a System Language that displays Numbers in a '30,6' or '$57,65' format, rather than '30.6' or '$57.65'? As I believe this to have been the issue for the OP and commenter on the 'Old Report'.

[[Old Report]](https://github.com/FuryFight3r/ScrappingSimulator/issues/64)

Are you able to provide your Player Logs and or Save File so I can look a little further into the cause of this issue? I may need to further modify the conversion method in y previous fix attempt, to make it so the Game Version gets converted before saving aswell as the current after loading so the script can have 2 chances at 'Parsing' (Converting) the Text value into a Number value which in theory should lower the risk of this bug continuing.

Quote from old report:

> Hi again @NiKoLiNhO666 and @GizmosGaming I hope you are both doing well. I have just released the v0.30.7 Update which should hopefully Patch the issue with not being able to load in due to the version checker failing, I wasn't able to fully test this on a different System Language, though I was able to replicate it by modifying my Save Files data to save the Version as '30,6' rather than '30.6' and the code I added seems to successfully convert the comma back to a full stop/period and I was able to load back and continue off where I had saved, so hopefully it is the same outcome for the both of you (and anyone else facing this issue). However if this still does not solve this issue please do let me know, I may need to look a bit deeper to the cause of the problem, the only Text Value being changed to a Number Value (Parse Conversion, which links up to @NiKoLiNhO666's error log) during the load process is the version checker, which is what lead me to believe this was the cause of the problem, it also corresponds to @GizmosGaming's Screenshot of the error happening after loading the Crucible in the Error Logs as the Converting of the Version is the next action after as seen in my attached photo, Thank you both for reporting this and fingers crossed you can get back to Scrapping :)
> 
> ![Screenshot_183](https://user-images.githubusercontent.com/44615800/189336500-5dace6a4-fff6-4500-a534-51d063b2e8c0.png)

**Comment by Etoilevent** [comment]
Gonna try and give you my log this week end :)

**Comment by FuryFight3r** [comment]
Thank you for confirming that @Etoilevent
Yeah it will certainly happen after purchasing the Crucible as only after owning the crucible does the Version check run, as the Crucible is the only Object that requires this version checker due to changes/updates that were made in an earlier update which rendered all saved Crucibles broken, so this version checker checks if the saved version was a version that contained the old crucible. If so it replaces it with the brand new, working crucible. In which case if the System Language changes this Text Value of 30.7 to 30,7 this makes it so the Text can no longer be converted to a Number value to be referenced in the sense of:

'if savedVersion is Less than 30.0 then execute this fixing code and then continue loading, otherwise if savedVersion is equal to or greater than 30.0 do nothing and load normally'.

The reason this needs to be converted to a Number Value and cannot remain a Text Value is because Text can only be used as 'if is NOT equal to 30.0' which means the fix code would run in the players version is 30.1, whereas a Number Value can be used in many other ways such as, Less than, equal to and greater than so the code only executes once to fix the problem if the player is coming from an older version.

I will rework the Version checker so it is independent from the Crucible and has its own loading section. Along with this I will see if I can add further checks to see if the supplied Saved Game Version _can_ be converted before attempting to force the conversion, as this failed Text to Number conversion attempt is what is causing the softlock when loading. 

I aim to have a patch out either today or tomorrow that fixes this and other active issues and hopefully have you Scrapping again in no time, thank you again for reporting this 🙂👍

**Comment by Etoilevent** [comment]
Nice if it's was helpfull.
Burning to finally try this furnace ahah :D 
but i have my time so take yours and thanks for the game :)

**Comment by FuryFight3r** [comment]
Hi again @Etoilevent 

I am hoping this latest update [v0.30.8](https://steamcommunity.com/games/1496640/announcements/detail/3302850737224474511) fixes this bug, I will leave the issue open for now to verify that it's working okay.

Thanks again for reporting this 🙂

**Comment by Etoilevent** [comment]
gonna try this asap :D
