### ISSUE TITLE
[Bug]: Scrap Numbers Not Adding Up

### ISSUE THREAD

**Issue by Bestywolf** [FuryFight3r/ScrappingSimulator#83]
### Describe the bug

I am taking apart the Wireless Router and noticed that some of the numbers weren't adding up correctly. I noticed this on two separate parts on the Wireless Router but am pretty sure I have seen this elsewhere.

### Reproduction Steps

1. Start Disassembling the Wireless Router
2.  Take out one of the Crystal Oscillators (Or IC Chips) on the Router Motherboard
3. Take out a second before the numbers on the bottom disappear.
4. The number do not correctly add up. (Different for each case) 

### Expected behaviour

Aluminum, Brass, and Silver should be at 1.06g
Gold should be at 0.22g
(Refer to the images for this to make more sense)

### Screenshot(s)/Video(s)

Screenshot of When I took off First IC Chip
![Screenshot 2022-11-12 171027](https://user-images.githubusercontent.com/116427861/201498247-f25e6874-847b-49c4-827a-ca7a785e1cae.png)
Screenshot of When I took off Second IC Chip
![Screenshot 2022-11-12 171050](https://user-images.githubusercontent.com/116427861/201498249-4b6e47e9-851e-4a2d-8aad-aa38b8588646.png)

### Console output

There were no Red Text or Errors Shown

### Player Logs

[New folder.zip](https://github.com/FuryFight3r/ScrappingSimulator/files/9996204/New.folder.zip)

This Zip file contains the Player Logs and my saved game File

**Comment by FuryFight3r** [comment]
Hi there @Bestywolf
Thank you for taking the time to report this, however this is just due to the way the numbers are displayed, for example if the Gold Given displays 0.11g this through the script may be more something like 0.106648363864 which in the terms of turning this into a 2 decimal value it is rounded up to be displayed as 0.11, then when that 0.10664..... value doubles to 0.21328.... that converted to 2 decimal places is closer to 0.21g rather than 0.22g 🙂👍
