### ISSUE TITLE
[Bug]: I'M FLYING !!!!!!

### ISSUE THREAD

**Issue by senoks** [FuryFight3r/ScrappingSimulator#92]
### Describe the bug

I was collecting a PC, sprinted home and suddenly i was flying over my garage :D
Lost the Computer on the garage roof and my character was transported to the bedroom.
It was a bit funny at the beginning, but now it's a bit annoying.

Sometimes i sprint with a heavy thing, like Server, TV or PC, My character can start flying. Not all the times, but sometimes. This happens only if I sprint the main street to your garage. It never happen if you are carrying small/light stuff, only the heavy ones (if you are sprinting home).

### Screenshot(s)/Video(s)

![Flying_High](https://user-images.githubusercontent.com/6820904/215357524-7c28c4de-fb67-4073-aa62-e89abb143e4f.jpg)

**Comment by FuryFight3r** [comment]
Hi there @senoks 

This is a known bug, it's due to the system that (is supposed to) disable the currently carried objects Colliders, though for some reason it sometimes doesn't disable the Objects colliders causing the player to be able to use the carried object to levitate/fly if the object is placed underneath the player.

To retrieve your PC from the Garage roof, I would suggest using E-Waste to 'Nerd Pole' yourself up onto the garage roof 🙂👍

**Comment by FuryFight3r** [comment]
Hi there @senoks thank you again for reporting this - This should now be fixed in the [v0.32 Major Update](https://steamcommunity.com/games/1496640/announcements/detail/3640634660759680357) :)
