### ISSUE TITLE
[Bug]: <controls are wigging out constantly while just using keyboard and mouse>

### ISSUE THREAD

**Issue by mrhood11** [FuryFight3r/ScrappingSimulator#97]
### Describe the bug

hi you might remember me from the steam review by A L E X 5 3 to answer your question from before yes i have my controllers unplugged everything ive rebooted my pc several times ive even redownloaded the game nothing seems to be working 

### Reproduction Steps

just playing the game

### Expected behaviour

character will straffe left and right on its own

### Screenshot(s)/Video(s)

https://medal.tv/games/requested/clips/YqiV0Fklemboq/d1337SpFW8Id?invite=cr-MSw1b28sMTI4OTc2NDI2LA

medal link of the input bug

### Player Logs

cant find it

**Comment by FuryFight3r** [comment]
Hi there @mrhood11 
Thank you for reporting this, that is certainly very weird, since you have ruled out being a controller issue, I am completely unsure as to what could be causing this, the only buttons hard coded into the game to accept left and right movement for the character are [A] and [D] and other reports of a similar issue have always been related to a PS Controller or XBOX Controller connected to their system causing the character to constantly move in a given direction (as no stick drift feathering has been coded into the game so the character picks up even the slightest stick drift even on brand new controllers as no single controller can have an exact perfect 0.00000000 X and Y positioning with their joy sticks). 

Which leads me to believe it could be related to some outside issue, potentially an external  program conflicting somewhere or potentially a faulty keyboard if it happens on other games also, though I am only assuming given the info provided and this being the very first issue of the character acting erraticly that hasn't been directly related to a connected controller.

Would you happen to have a 3rd party program that is manipulating/ modifying your Keybinds? 

You can also find your Save File/Player Logs Here:
https://github.com/FuryFight3r/ScrappingSimulator/wiki/Where-to-find-Scrapping-Simulator-Save-File-and-Error-Logs

**Comment by mrhood11** [comment]
i have no external program running keybinds and i have unplugged my keyboard before it did nothing.if this helps i use a keyboard from 1987 an ibm model M throught the PS/2 port on my msi b40m motherboard but yet again ive never had this issue in unity games

**Comment by FuryFight3r** [comment]
I personally don't have much experience with outdated technologies so it's hard to say weather that's the problem or not.

The only thing I could suggest from this point would be to try the game on another system if at all possible, if the problem persists across different systems than it is certainly a coding issue with the game that I may be able to fix easily, though if it is an issue between the game and your system specifically, then there is not much I am able to do unfortunately without knowing your system to create a workaround in-game.

**Comment by mrhood11** [comment]
is there a log that gets created in the game files i can send you by any chance?

**Comment by FuryFight3r** [comment]
Yeah, I had linked a Wiki guide on how to find the Player Logs in my first comment:
https://github.com/FuryFight3r/ScrappingSimulator/issues/97#issuecomment-1457628085

Hopefully I can spot something within that to help fix the bug 🙂👍

**Comment by mrhood11** [comment]
[Player-prev.log](https://github.com/FuryFight3r/ScrappingSimulator/files/10915119/Player-prev.log)
[Player.log](https://github.com/FuryFight3r/ScrappingSimulator/files/10915131/Player.log)
here you go i managed to make a save game now its constantly trying to go backwards

**Comment by mrhood11** [comment]
i think i may have resolved the issue its now not doing anything on its own anymore i think it was handbrake that i forgot that was still plugged in cause the character would move forward if i were to pull the handbrake so i think it was that ill keep you posted on this

**Comment by FuryFight3r** [comment]
Thank you for that, that is certainly strange, could you also possibly send in your save file? If the behaviour changes after saving then it could potentially be an Object stuck to the player causing interference.

I will look into the logs and see if anything stands out

**Comment by mrhood11** [comment]
so the game seems to be picky with anybody with a wheel setup you have to make sure your wheel and handbrake or any sim controllers are unplugged if you want to play this 
i tried putting my save in here but the file type is not supported on here

**Comment by FuryFight3r** [comment]
> 

Yeah I should have been more specific when I said unplug all other devices from your system, as a wheel setup acts exactly like a controller in the case of Scrapping Simulator, anything with a joystick like input will send false signals to the game, and frustratingly enough I cannot seem to disable controller input through Unity.

**Comment by mrhood11** [comment]
well thanks for all the help i wish you luck to finishing the game i changed my review to recommended

**Comment by FuryFight3r** [comment]
Thank you I appreciate that, I am glad its working for you now, I will do my best to try force Unity to disable any input that is not directly from a Keyboard and Mouse, though I have tried many a time in the past with no success, if all else fails I will put a warning on the game start-up that recommends disconnecting any Controller like Input device for best game experience.
